# Generated by Django 4.1 on 2022-09-16 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login_tb',
            new_name='admin_tb',
        ),
    ]
