# Generated by Django 4.1 on 2022-09-17 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0005_state_tb'),
    ]

    operations = [
        migrations.DeleteModel(
            name='state_tb',
        ),
    ]
