# Generated by Django 4.1 on 2022-09-17 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0007_state_tb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state_tb',
            name='countryid',
        ),
        migrations.DeleteModel(
            name='country_tb',
        ),
        migrations.DeleteModel(
            name='state_tb',
        ),
    ]
