# Generated by Django 4.1 on 2022-09-17 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0008_remove_state_tb_countryid_delete_country_tb_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='hobbie_tb',
            new_name='hobbiename_tb',
        ),
    ]
