# Generated by Django 4.1 on 2022-09-19 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0009_rename_hobbie_tb_hobbiename_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='hobbiefactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_name', models.CharField(max_length=50)),
                ('hobbie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.hobbiename_tb')),
            ],
        ),
    ]
