# Generated by Django 4.1 on 2022-09-21 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0004_hobbie_tb'),
        ('siteadmin', '0012_seasonfactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='seasoncountry_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('countryid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.country_tb')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasonfactor_tb')),
                ('seasonid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.season_tb')),
                ('stateid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.state_tb')),
            ],
        ),
    ]
