# Generated by Django 4.1 on 2022-09-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0013_seasoncountry_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='age_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_age', models.IntegerField()),
                ('max_age', models.IntegerField()),
                ('factor_name', models.CharField(max_length=50)),
            ],
        ),
    ]
