# Generated by Django 4.1 on 2022-09-17 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0002_register_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_tb',
            name='answer',
            field=models.CharField(default='abc', max_length=50),
        ),
        migrations.AddField(
            model_name='register_tb',
            name='gender',
            field=models.CharField(default='abc', max_length=50),
        ),
    ]
