# Generated by Django 4.1 on 2022-09-28 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0007_contact_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=50)),
                ('remarks', models.CharField(max_length=50)),
                ('contactid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactid1', to='siteuser.register_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid1', to='siteuser.register_tb')),
            ],
        ),
    ]
