# Generated by Django 4.1 on 2022-09-28 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0008_blacklist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='contactid',
            new_name='contactid1',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='userid',
            new_name='userid1',
        ),
    ]
