# Generated by Django 4.1 on 2022-09-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0009_rename_contactid_blacklist_contactid1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blacklist',
            old_name='contactid1',
            new_name='contactid',
        ),
        migrations.RenameField(
            model_name='blacklist',
            old_name='userid1',
            new_name='userid',
        ),
    ]
