# Generated by Django 4.1 on 2022-09-28 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteuser', '0010_rename_contactid1_blacklist_contactid_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='blacklist',
            new_name='blacklist_tb',
        ),
    ]
