# Generated by Django 4.1 on 2022-09-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('siteadmin', '0014_age_tb'),
        ('siteuser', '0014_customeragefactor_tb'),
    ]

    operations = [
        migrations.CreateModel(
            name='customercountryfactor_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factorid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteadmin.seasoncountry_tb')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteuser.register_tb')),
            ],
        ),
    ]
